import {useEffect,useMemo,useState} from "react";
import {Box,ChevronLeft,ExternalLink,History,Mail,Phone,ShoppingBag,StickyNote,Tag,UserRound,X} from "lucide-react";
import type {PanelUser} from "../../../shared/contracts/domain";
import {api} from "../../lib/api";

type TagItem={id:string;name:string;color:string};
type CustomerNote={id:string;username:string;text:string;created_at:string;visibility:"SHARED"|"PERSONAL"};

export function CustomerSidebar({conversation,user,onChanged,onBack}:{conversation?:any;user:PanelUser;onChanged:()=>Promise<void>|void;onBack?:()=>void}){
  const[context,setContext]=useState<any>(),[tags,setTags]=useState<TagItem[]>([]),[notes,setNotes]=useState<CustomerNote[]>([]),[selectedTag,setSelectedTag]=useState(""),[noteText,setNoteText]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
  useEffect(()=>{setContext(undefined);setNotes([]);setError("");if(!conversation?.id)return;void Promise.all([api(`/conversations/${conversation.id}/customer-context`).then(setContext).catch(()=>setContext({status:"forbidden"})),api<{items:TagItem[]}>("/tags").then(result=>setTags(result.items)),api<{items:CustomerNote[]}>(`/conversations/${conversation.id}/customer-notes`).then(result=>setNotes(result.items))]).catch(reason=>setError(reason instanceof Error?reason.message:"Müşteri bilgileri yüklenemedi."))},[conversation?.id]);
  const canTag=user.role==="admin"||user.permissions["customer_hub:manage_tags"]===true;const canAssign=user.role==="admin"||user.permissions["customer_hub:assign"]===true;
  const availableTags=useMemo(()=>tags.filter(tag=>!conversation?.tags?.some((current:TagItem)=>current.id===tag.id)),[tags,conversation?.tags]);
  if(!conversation)return <aside className="customer-sidebar"/>;
  const meta=conversation.metadata??{};const productName=meta.productName??meta.product_name??meta.product_title;const productId=meta.productMainId??meta.product_id??meta.product_handle??meta.sku;
  const mutate=async(action:()=>Promise<unknown>)=>{setBusy(true);setError("");try{await action();await onChanged()}catch(reason){setError(reason instanceof Error?reason.message:"İşlem tamamlanamadı.")}finally{setBusy(false)}};
  const addTag=()=>{if(!selectedTag)return;void mutate(async()=>{await api(`/conversations/${conversation.id}/tags/${selectedTag}`,{method:"PUT",body:JSON.stringify({})});setSelectedTag("")})};
  const removeTag=(tagId:string)=>void mutate(()=>api(`/conversations/${conversation.id}/tags/${tagId}`,{method:"DELETE"}));
  const assign=()=>void mutate(()=>api(`/conversations/${conversation.id}/assignment`,{method:"PUT",body:JSON.stringify({assigned_user_id:conversation.assigned_user_id===user.id?null:user.id})}));
  const addCustomerNote=async()=>{const value=noteText.trim();if(!value)return;setBusy(true);setError("");try{const created=await api<CustomerNote>(`/conversations/${conversation.id}/customer-notes`,{method:"POST",body:JSON.stringify({text:value})});setNotes(current=>[...current,created]);setNoteText("")}catch(reason){setError(reason instanceof Error?reason.message:"Müşteri notu kaydedilemedi.")}finally{setBusy(false)}};
  return <aside className="customer-sidebar"><header><button className="mobile-context-back" onClick={onBack} aria-label="Konuşmaya dön"><ChevronLeft/>Konuşma</button><span>MÜŞTERİ BİLGİSİ</span>{conversation.external_url?<a className="icon-button" href={conversation.external_url} target="_blank" rel="noreferrer" aria-label="Kanaldaki kaydı aç"><ExternalLink size={16}/></a>:<span/>}</header>
    <div className="customer-identity"><div className="avatar xl">{conversation.display_name.slice(0,2).toUpperCase()}</div><h3>{conversation.display_name}</h3><p>{conversation.channel_name} müşterisi</p></div>
    <div className="info-list">{conversation.email&&<div><Mail/><span>{conversation.email}</span></div>}{conversation.phone&&<div><Phone/><span>{conversation.phone}</span></div>}{conversation.customer_identifier&&<div><UserRound/><span>{conversation.customer_identifier}</span></div>}</div>
    <section><h4><ShoppingBag/>Panel / sipariş bağlamı</h4>{!context&&<p className="muted">Panel kontrol ediliyor…</p>}{context?.status==="unavailable"&&<div className="context-unavailable">Panel şu anda erişilemiyor</div>}{context?.status==="forbidden"&&<div className="context-unavailable">Bu bağlamı görüntüleme yetkiniz yok.</div>}{context?.status==="not_linked"&&<p className="muted">Panel müşterisiyle henüz eşleşmedi.</p>}{context?.status==="ok"&&<PanelContext data={context.data}/>}</section>
    {(productName||productId)&&<section><h4><Box/>İlgili ürün</h4><div className="product-card"><div className="product-placeholder"><Box/></div><div><strong>{productName??productId}</strong>{productId&&<span>ID / SKU: {productId}</span>}{meta.barcode&&<span>Barkod: {meta.barcode}</span>}{(meta.variant_id||meta.variant)&&<span>Varyant: {meta.variant_id||meta.variant}</span>}</div></div>{(meta.webUrl||conversation.external_url)&&conversation.channel_type==="TRENDYOL"&&<a className="context-link" href={meta.webUrl||conversation.external_url} target="_blank" rel="noreferrer">Trendyol’da Aç <ExternalLink size={12}/></a>}</section>}
    <section><h4><History/>Geçmiş konuşmalar</h4>{conversation.conversation_history?.length?<div className="conversation-history">{conversation.conversation_history.map((item:any)=><div key={item.id}><strong>{item.channel_name}</strong><span>{item.subject||item.status} · {formatTime(item.last_message_at)}</span></div>)}</div>:<p className="muted">Başka konuşma bulunamadı.</p>}</section>
    <section><h4><Tag/>Etiketler</h4><div className="sidebar-tags">{conversation.tags?.map((item:TagItem)=><span key={item.id} style={{"--tag":item.color} as React.CSSProperties}>{item.name}{canTag&&<button aria-label={`${item.name} etiketini kaldır`} disabled={busy} onClick={()=>removeTag(item.id)}><X size={10}/></button>}</span>)}</div>{canTag&&<div className="sidebar-inline-form"><select value={selectedTag} onChange={event=>setSelectedTag(event.target.value)} disabled={busy}><option value="">Etiket seçin</option>{availableTags.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><button onClick={addTag} disabled={busy||!selectedTag}>Ekle</button></div>}</section>
    <section><h4><UserRound/>Atanan kişi</h4><div className="assignment-card"><span>{conversation.assigned_user_id===user.id?"Size atanmış":conversation.assigned_user_id?`Kullanıcı: ${conversation.assigned_user_id}`:"Atanmamış"}</span>{canAssign&&(!conversation.assigned_user_id||conversation.assigned_user_id===user.id)&&<button onClick={assign} disabled={busy}>{conversation.assigned_user_id===user.id?"Atamayı Bırak":"Kendime Ata"}</button>}</div></section>
    <section><h4><StickyNote/>Müşteri Notları</h4><div className="customer-notes">{notes.map(item=><article key={item.id}><strong>{item.username}</strong><time>{formatTime(item.created_at)}</time><p>{item.text}</p>{item.visibility==="PERSONAL"&&<small>Kişisel e-posta kapsamı</small>}</article>)}{!notes.length&&<p className="muted">Henüz müşteri notu yok.</p>}</div><div className="customer-note-form"><textarea value={noteText} maxLength={10000} placeholder="Müşteri profiline not ekleyin…" onChange={event=>setNoteText(event.target.value)}/><button onClick={()=>void addCustomerNote()} disabled={busy||!noteText.trim()}>Not ekle</button></div></section>
    {error&&<div className="sidebar-error" role="alert">{error}</div>}
  </aside>;
}

function PanelContext({data}:{data:any}){
  const customer=data?.customer??data;const rawOrders=data?.orders??data?.recent_orders??data?.recentOrders??(data?.order?[data.order]:[]);const orders=Array.isArray(rawOrders)?rawOrders:[];const totalOrders=data?.total_orders??data?.totalOrders;const totalSales=data?.total_sales??data?.totalSales;
  return <div className="panel-context">{(totalOrders!==undefined||totalSales!==undefined)&&<div className="order-summary">{totalOrders!==undefined&&<div><strong>{String(totalOrders)}</strong><span>Sipariş</span></div>}{totalSales!==undefined&&<div><strong>{formatMoney(totalSales)}</strong><span>Toplam satış</span></div>}</div>}{(customer?.name||customer?.display_name||customer?.email||customer?.phone)&&<div className="context-details customer-context-details"><strong>{customer.name??customer.display_name}</strong>{customer.email&&<span>{customer.email}</span>}{customer.phone&&<span>{customer.phone}</span>}</div>}{orders.length?<div className="context-orders">{orders.map((order:any,index:number)=><OrderCard key={String(order.id??order.order_id??order.order_number??index)} order={order}/>)}</div>:totalOrders===undefined&&<p className="muted">Panel müşteri kaydı bulundu; sipariş detayı dönmedi.</p>}</div>;
}
function OrderCard({order}:{order:any}){const number=order.order_number??order.order_no??order.order_code??order.id;const date=order.order_date??order.created_at??order.date;const status=order.status??order.order_status;const tracking=order.tracking_number??order.cargo_tracking_number??order.shipment?.tracking_number;const rawItems=order.items??order.line_items??order.products??[];const items=Array.isArray(rawItems)?rawItems:[];return <article className="context-order"><header><strong>{number?`Sipariş ${number}`:"Sipariş"}</strong>{status&&<span>{status}</span>}</header>{date&&<time>{formatTime(date)}</time>}{items.map((item:any,index:number)=><div className="context-order-item" key={String(item.id??item.sku??index)}><strong>{item.product_name??item.name??item.title??item.sku}</strong><span>{[item.sku&&`SKU: ${item.sku}`,(item.variant??item.variant_name??item.size)&&`Varyant: ${item.variant??item.variant_name??item.size}`,(item.quantity??item.qty)!==undefined&&`Adet: ${item.quantity??item.qty}`,item.amount!==undefined&&formatMoney(item.amount)].filter(Boolean).join(" · ")}</span></div>)}{tracking&&<span className="tracking">Takip: {tracking}</span>}</article>}
function formatMoney(value:unknown){if(typeof value==="number")return new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY"}).format(value);return String(value)}
function formatTime(value:string){const parsed=new Date(/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/.test(value)?`${value.replace(" ","T")}Z`:value);return Number.isNaN(parsed.getTime())?value:parsed.toLocaleString("tr-TR",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"})}
