import test from"node:test";import assert from"node:assert/strict";import{randomUUID}from"node:crypto";import{testDatabase}from"../test-utils.js";import{createAdapterRegistry}from"../channels/core/registry.js";import{OutboxWorker}from"../outbox/worker.js";import{createApp}from"../app.js";
test("readonly user cannot queue outbound even with reply flag",async()=>{const{db,config}=testDatabase();const readonly={id:"read",username:"Read",role:"readonly"as const,permissions:{"customer_hub:view":true,"customer_hub:reply":true}};const registry=createAdapterRegistry(config),worker=new OutboxWorker(db,registry,config);const server=createApp({db,config,registry,worker,verify:async()=>readonly}).listen(0);const address=server.address();if(!address||typeof address==="string")throw new Error("server");const conversation=(db.prepare("SELECT id FROM conversations LIMIT 1").get()as any).id;const response=await fetch(`http://127.0.0.1:${address.port}/api/conversations/${conversation}/replies`,{method:"POST",headers:{"content-type":"application/json",cookie:"test_session=x",origin:config.appOrigin},body:JSON.stringify({body:"Yetkisiz",client_message_id:randomUUID()})});assert.equal(response.status,403);server.closeAllConnections();await new Promise<void>(resolve=>server.close(()=>resolve()));db.close();});
test("Panel outage degrades only customer context, not inbox",async()=>{const{db,config}=testDatabase();const admin={id:"admin",username:"Admin",role:"admin"as const,permissions:{}};const registry=createAdapterRegistry(config),worker=new OutboxWorker(db,registry,config);const server=createApp({db,config,registry,worker,verify:async()=>admin}).listen(0);const address=server.address();if(!address||typeof address==="string")throw new Error("server");const row=db.prepare("SELECT id,contact_id FROM conversations LIMIT 1").get()as any;db.prepare("UPDATE contacts SET panel_customer_id='panel-customer' WHERE id=?").run(row.contact_id);const headers={cookie:"test_session=x"};const[inbox,context]=await Promise.all([fetch(`http://127.0.0.1:${address.port}/api/conversations`,{headers}),fetch(`http://127.0.0.1:${address.port}/api/conversations/${row.id}/customer-context`,{headers})]);assert.equal(inbox.status,200);assert.equal(context.status,200);assert.equal((await context.json()as any).status,"unavailable");server.closeAllConnections();await new Promise<void>(resolve=>server.close(()=>resolve()));db.close();});

test("email multipart reply accepts attachment-only atomically and rejects fake content and non-email channels",async()=>{const{db,config}=testDatabase();const admin={id:"admin",username:"Admin",role:"admin"as const,permissions:{}};const registry=createAdapterRegistry(config),worker=new OutboxWorker(db,registry,config);const server=createApp({db,config,registry,worker,verify:async()=>admin}).listen(0);const address=server.address();if(!address||typeof address==="string")throw new Error("server");const base=`http://127.0.0.1:${address.port}`;const email=(db.prepare("SELECT c.id,a.id account_id FROM conversations c JOIN channel_accounts a ON a.id=c.channel_account_id WHERE a.channel_type='EMAIL'").get()as any);const website=(db.prepare("SELECT c.id FROM conversations c JOIN channel_accounts a ON a.id=c.channel_account_id WHERE a.channel_type='WEBSITE'").get()as any).id;db.prepare("UPDATE channel_accounts SET owner_user_id='admin' WHERE id=?").run(email.account_id);db.prepare("UPDATE conversations SET metadata_json=? WHERE id=?").run(JSON.stringify({reply_to:"customer@example.test"}),email.id);
  const send=async(conversationId:string,content:Buffer,type:string,name:string)=>{const form=new FormData();form.set("body","");form.set("client_message_id",randomUUID());form.append("attachments",new Blob([content],{type}),name);return fetch(`${base}/api/conversations/${conversationId}/replies`,{method:"POST",headers:{cookie:"test_session=x",origin:config.appOrigin},body:form})};
  const accepted=await send(email.id,Buffer.from("%PDF-1.7\nreport"),"application/pdf","report.pdf");assert.equal(accepted.status,202);const queued=await accepted.json()as any;const message=db.prepare("SELECT body_text,status FROM messages WHERE id=?").get(queued.id)as any;assert.deepEqual(message,{body_text:"",status:"QUEUED"});assert.equal((db.prepare("SELECT count(*) count FROM attachments WHERE message_id=?").get(queued.id)as any).count,1);assert.equal((db.prepare("SELECT count(*) count FROM outbox_jobs WHERE message_id=?").get(queued.id)as any).count,1);
  const detail=await fetch(`${base}/api/conversations/${email.id}`,{headers:{cookie:"test_session=x"}});const detailBody=await detail.json()as any;assert.equal(detailBody.messages.find((item:any)=>item.id===queued.id).attachments[0].filename,"report.pdf");
  const fake=await send(email.id,Buffer.from("<html>bad</html>"),"application/pdf","fake.pdf");assert.equal(fake.status,415);assert.equal((await fake.json()as any).error.code,"ATTACHMENT_CONTENT_MISMATCH");
  const unsupported=await send(website,Buffer.from("%PDF-1.7\nreport"),"application/pdf","report.pdf");assert.equal(unsupported.status,400);assert.equal((await unsupported.json()as any).error.code,"CHANNEL_NOT_SUPPORTED");
  server.closeAllConnections();await new Promise<void>(resolve=>server.close(()=>resolve()));db.close();});
